### ISSUE TITLE
No semicolon in .scss files (sass)

### ISSUE THREAD

**Issue by tigrr** [hayaku/hayaku#265]
In normal css mode a semicolon is inserted at the end of a declaration. But in sass no semicolon is inserted. (.scss, in contrast to .sass, does use semicolons)

**Comment by name-k** [comment]
It seems, this issue was not fixed. Is there any workaround?

**Comment by tigrr** [comment]
I realized that it was my mistake soon after opening the issue.
The mistake was that I was selecting "SASS" syntax rather than "SCSS". If you set syntax to "SCSS", the semicolon will be inserted.

**Comment by name-k** [comment]
@tigrr Yes, indeed. I made same mistake. Thank you!
