### ISSUE TITLE
! + tab -> !important

### ISSUE THREAD

**Issue by Calvein** [hayaku/hayaku#298]
Right now it's going to a new line, so I guess it's trying to do something but fails.

Tested on ST3 with CSS and Stylus (I saw other task that may talk about it but they're in Russian).

**Comment by igoradamenko** [comment]
It works w/o [tab]. When you enter `!` after property value hayaku complete it to `!important`.

**Comment by Calvein** [comment]
I guess it make sense, what I meant was this (`->` when I tab):
```
// What I do
w100 -> width 100px
width 100px ! -> width 100px !
// What I wanted
w100! -> width 100px !important
```

But it make sense, I'm closing it.
