### ISSUE TITLE
Doesn't work with postcss syntax

### ISSUE THREAD

**Issue by TrySound** [hayaku/hayaku#308]
I use [Syntax Highlighting for PostCSS](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS) with ST3. Hayaku doesn't work on tab. Everything is fine if I switch syntax to `css`. Can I somehow configure for postcss?

**Comment by kizu** [comment]
Thanks for the report, the fix would be in the next release (1.5.3) soon in Package Control.

**Comment by TrySound** [comment]
@kizu Thanks!
